USE MarketDB
GO


CREATE TABLE Basket
(
ID INT PRIMARY KEY IDENTITY NOT NULL,
userID INT REFERENCES UserMarket(ID) ON DELETE CASCADE,
);

CREATE TABLE BasketItem
(
ID INT PRIMARY KEY IDENTITY NOT NULL,
itemID INT REFERENCES Item(ID) ON DELETE NO ACTION,
basketID INT REFERENCES Basket(ID) ON DELETE CASCADE,
);

CREATE TABLE Rating
(
ID INT PRIMARY KEY IDENTITY NOT NULL,
userID INT REFERENCES UserMarket(ID) ON DELETE NO ACTION,
itemID INT REFERENCES Item(ID) ON DELETE CASCADE,
rate DECIMAL(4,1),
comment TEXT 
);


DROP TABLE Basket
DROP TABLE BasketItem
DROP TABLE Rating