

USE MarketDB
GO
CREATE TABLE UserMarket
(
ID INT PRIMARY KEY IDENTITY NOT NULL,
name VARCHAR(50) NOT NULL UNIQUE,
email VARCHAR(200) NOT NULL UNIQUE,
password VARCHAR(100) NOT NULL,
role VARCHAR(50) NOT NULL  DEFAULT ('USER')
);

DROP TABLE UserMarket